#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

use ScreenJSON\Commands;

$application = new Application();

$application->add (new Commands\Decrypt);
$application->add (new Commands\Encrypt);
$application->add (new Commands\Export);
$application->add (new Commands\Import);
$application->add (new Commands\Validate);

$application->run();